# Facebook (+ Wit)
ACCESS_TOKEN = '<<ACCESS_TOKEN>>'
VERIFY_TOKEN = '<<VERIFY_TOKEN>>'
WIT_AI_ACCESS_TOKEN = 'E7GDGT4YT7AW5XOLXX7Y4Y72SVHXY4N7'
#E7GDGT4YT7AW5XOLXX7Y4Y72SVHXY4N7
#IKJJJYYVR3X672DHFVS7U7C4L2MQSS2P

# Offline data sources
FACTS_SOURCE_FILE = 'data/facts.json'
JOKES_SOURCE_FILE = 'data/jokes.json'
QUOTES_SOURCE_FILE = 'data/quotes.json'

# API Keys
GOODREADS_ACCESS_TOKEN = '<<GOODREADS_ACCESS_TOKEN>>'
GOOGLE_URL_SHORTENER_API_KEY = '<<GOOGLE_URL_SHORTENER_API_KEY>>'
MAPQUEST_CONSUMER_KEY = 'lkmKPbsqkFfSCVCil7tDGL0WDm5v0pAQ'
MUSIXMATCH_API_KEY = '<<MUSIXMATCH_API_KEY>>'
NEWS_API_KEY = '<<NEWS_API_KEY>>'
OPEN_WEATHER_MAP_ACCESS_TOKEN = '92359105f246d79ec0e6937869e1f8d3'
TIME_ZONE_DB_API_KEY = 'TE46BP521HIK'
WORDS_API_KEY = '<<WORDS_API_KEY>>'
YOUTUBE_DATA_API_KEY = '<<YOUTUBE_DATA_API_KEY>>'
